export const REQUEST_CONTENT_LIST = 'REQUEST_CONTENT_LIST'
export const CHANGE_DATA_TWO = 'CHANGE_DATA_TWO'
export const GET_DATA_FOR_TESTBOX = 'GET_DATA_FOR_TESTBOX'
export const GET_ARR_DATA = 'GET_ARR_DATA'
export const GET_DATA_FROM_API = "GET_DATA_FROM_API"