export const REQUEST_CONTENT_LIST = 'REQUEST_CONTENT_LIST'
export const CHANGE_DATA_TWO = 'CHANGE_DATA_TWO'
export const SET_DATA_FOR_TESTBOX = 'GET_DATA_FOR_TESTBOX'
export const SET_ARR_DATA = 'GET_ARR_DATA'
export const SET_DATA_FROM_API = "SET_DATA_FROM_API"
export const SET_DATA_FROM_DATA_TWO = "SET_DATA_FROM_DATA_TWO"
export const SET_REQ_STATE = "SET_REQ_STATE"